server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: 192.168.253.134
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders: # rabbitmq
        defaultRabbit: # binding
          type: rabbit #服务的整合处理
      bindings: #
        input: #这个名字是一个通道的名称，在分析具体源代码的时候会进行说明
          destination: studyExchange # Exchange
          content-type: application/json # jsontext/plain
          binder: defaultRabbit #
          group: consumer
eureka:
  client: # Eureka
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 30
    lease-expiration-duration-in-seconds: 5 # 590
    instance-id: receive-8802.com  #
    prefer-ip-address: true     # IP
