server:
  port: 8089
  context-path: /learnMore
#  ssl:
#    key-store: .keystore
#    key-store-password: 123456
#    key-store-type: JKS
#    key-alias: ssldemo
spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    show-sql: true
#spring.jpa.properties.*
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.use-new-id-generator-mappings=true
---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
person:
  name: fengjie
  age: 24
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
#person:
#  name: someone
#  age: 999
