server:
  port: 8089
  context-path: /learnMore
#  ssl:
#    key-store: .keystore
#    key-store-password: 123456
#    key-store-type: JKS
#    key-alias: ssldemo
spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    generate-ddl: true
#     妈的竟然不管用，哪儿的问题呢,妈个鸡把entityManagerFactory的配置去了就好了！！！！
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 192.168.25.4
    port: 6379
    timeout: 3000
#thymeleaf配置
  thymeleaf:
    cache: false
#日志配置
logging:
  level:
    org.springframework.security: info
---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
person:
  name: fengjie
  age: 24
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
#person:
#  name: someone
#  age: 999
