server:
  port: 9527
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eurekanode0.com:7001/eureka,http://eurekanode1.com:7002/eureka/,http://eurekanode2.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
info:
  app.name: microservice-zuul
  company.name: www.learn.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
zuul:
  routes:
    servicdept.serviceId: microservice-dept #TODO servicdept这个前缀的作用是？
    servicdept.path: /servicedept/** #**代表可以级联访问，*只能访问一级
#  设置忽略的服务（访问时隐藏真实的服务，使其无法访问，只能通过设置的path访问，可以用*表示隐藏全部真实服务名）
  ignored-services: microservice-dept
#  设置指定前缀
  prefix: /learncloud