server:
  port: 8091
  context-path: /cloudMarket-report
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active: dev
  application:
    name: cloud-report
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.Oracle10gDialect
  output:
    ansi:
      enabled: always
banner:
  charset: utf-8
  location: banner.txt
cloud-report:
    app:
      name: cloud-report
      version: 1.4-SNAPSHOT
---
spring:
  profiles: dev
influxDB:
  url:
  username:
  password:
  database: