server:
  port: 8091
  context-path: /cloudMarket-report
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active: dev
  application:
    name: cloud-report
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.Oracle10gDialect
  output:
    ansi:
      enabled: always
banner:
  charset: utf-8
  location: banner.txt
cloud-report:
    app:
      name: cloud-report
      version: 1.4-SNAPSHOT
---
spring:
  profiles: dev
  datasource:
   monitor:
    url: jdbc:oracle:thin:@11.11.176.14:1521:cmall
    username: portaldev
    password: portaldev
    schema: portaldev
   cloud:
    url: jdbc:oracle:thin:@11.11.176.14:1521:cmall
    username: portaldev
    password: portaldev
    schema: portaldev
  rabbitmq:
    host: 11.11.176.209
    port: 5672
    username: guest
    password: guest
    virtual-host: /
debug: true
zabbix:
  user: api_user
  password: API_user
  url: http://11.11.165.16/api_jsonrpc.php
VCMonitor:
  url: http://127.0.0.1:8080/cloudAutoEngine/vsphere/retrieveVMPerfFromVC_VMPerfRetrieve
---
spring:
  profiles: test-kylin
  datasource:
   monitor:
    url: jdbc:oracle:thin:@11.11.156.7:1521:orcl
    username: portaldev
    password: portaldev
    schema: portaldev
   cloud:
    url: jdbc:oracle:thin:@11.11.156.7:1521:orcl
    username: portaldev
    password: portaldev
    schema: portaldev
  rabbitmq:
    host: 11.11.156.7
    port: 5672
    username: guest
    password: guest
    virtual-host: /
debug: true
zabbix:
  user: api_user
  password: API_user
  url: http://11.11.165.16/api_jsonrpc.php
VCMonitor:
  url: http://11.11.156.6:8080/cloudAutoEngine/vsphere/retrieveVMPerfFromVC_VMPerfRetrieve
---
spring:
  profiles: test
  datasource:
   monitor:
    url: jdbc:oracle:thin:@11.11.175.105:1521:orcl
    username: portaldev
    password: portaldev
    schema: portaldev
   cloud:
    url: jdbc:oracle:thin:@11.11.175.105:1521:orcl
    username: portaldev
    password: portaldev
    schema: portaldev
  rabbitmq:
    host: 11.11.175.101
    port: 5672
    username: portaldev
    password: portaldev
    virtual-host: test
zabbix:
  user: api_user
  password: API_user
  url: http://11.11.165.16/api_jsonrpc.php
VCMonitor:
  url: http://11.11.175.101:8082/cloudAutoEngine/vsphere/retrieveVMPerfFromVC_VMPerfRetrieve
---
spring:
  profiles: autotest
  datasource:
   monitor:
    url: jdbc:oracle:thin:@11.11.175.105:1521:orcl
    username: portaltest
    password: portaltest
    schema: portaltest
   cloud:
    url: jdbc:oracle:thin:@11.11.175.105:1521:orcl
    username: portaltest
    password: portaltest
    schema: portaltest
  rabbitmq:
    host: 11.11.175.98
    port: 5672
    username: portaltest
    password: portaltest
    virtual-host: autotest
zabbix:
  user: api_user
  password: API_user
  url: http://11.11.165.16/api_jsonrpc.php
VCMonitor:
  url: http://11.11.175.98:8082/cloudAutoEngine/vsphere/retrieveVMPerfFromVC_VMPerfRetrieve
---
spring:
  profiles: test_his
  datasource:
   monitor:
      url: jdbc:oracle:thin:@11.11.162.62:1521/cloudhis
      username: cloudhis
      password: cloudhis
      schema: cloudhis
   cloud:
      url: jdbc:oracle:thin:@11.11.162.62:1521/clouddb
      username: cnpccloud3
      password: oracle3
      schema: cnpccloud3
  rabbitmq:
    host: 11.11.176.39
    port: 5672
    username: tcloudadmin
    password: passw0rd
    virtual-host: /
zabbix:
  user: api_user
  password: API_user
  url: http://11.11.165.16/api_jsonrpc.php
VCMonitor:
  url: http://11.11.176.100:8080/cloudAutoEngine/vsphere/retrieveVMPerfFromVC_VMPerfRetrieve
---
spring:
  profiles: pro
  datasource:
   monitor:
    url: jdbc:oracle:thin:@11.11.162.62:1521/cloudhis
    username: cloudhis
    password: Richfit1234
    schema: cloudhis
   cloud:
    url: jdbc:oracle:thin:@11.11.162.62:1521/clouddb
    username: cnpccloud3
    password: Richfit1234
    schema: cnpccloud3
  rabbitmq:
    host: 11.11.162.251
    port: 5672
    username: cloudadmin
    password: passw0rd@123
    virtual-host: /
zabbix:
  user: api_user
  password: API_user
  url: http://11.11.165.16/api_jsonrpc.php
VCMonitor:
  url: http://11.11.162.133:8080/cloudAutoEngine/vsphere/retrieveVMPerfFromVC_VMPerfRetrieve
---
spring:
  profiles: repro
  datasource:
   monitor:
    url: jdbc:oracle:thin:@11.11.163.13:1521/cloudhis
    username: cloudhis
    password: cloudhis
    schema: cloudhis
   cloud:
    url: jdbc:oracle:thin:@11.11.163.13:1521/orcl
    username: cnpccloud3
    password: oracle3
    schema: cnpccloud3
  rabbitmq:
    host: 11.11.163.13
    port: 5672
    username: guest
    password: guest
    virtual-host: /
zabbix:
  user: api_user
  password: API_user
  url: http://11.11.165.16/api_jsonrpc.php
VCMonitor:
  url: http://11.11.163.13:8082/cloudAutoEngine/vsphere/retrieveVMPerfFromVC_VMPerfRetrieve
---
spring:
  profiles: perf
  datasource:
   monitor:
    url: jdbc:oracle:thin:@11.11.176.44:1521:cmall
    username: portaldev
    password: portaldev
    schema: portaldev
   cloud:
    url: jdbc:oracle:thin:@11.11.176.44:1521:cmall
    username: portaldev
    password: portaldev
    schema: portaldev
  rabbitmq:
    host: 11.11.176.39
    port: 5672
    username: tcloudadmin
    password: passw0rd
    virtual-host: /
zabbix:
  user: api_user
  password: API_user
  url: http://11.11.165.16/api_jsonrpc.php
VCMonitor:
   url: http://11.11.176.24:8080/cloudAutoEngine/vsphere/retrieveVMPerfFromVC_VMPerfRetrieve