server:
  port: 8888
  context-path: /learnMore

spring:
  profiles:
    active: dev

---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
---
spring:
  profiles: dev
  datasource:
    name: riewa
    url: jdbc:mysql://192.168.253.134:3306/riewa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver