spring:
  datasource:
    url: jdbc:mysql://47.94.83.109:3306/sso
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 47.94.83.109
    password: 1qaz@WSX
    port: 6379
server:
  port: 8888